### ISSUE TITLE
This needs a website!

### ISSUE THREAD

**Issue by JohannesHoppe** [maartentibau/angular-logos#19]
Where you can look at all the logos at once to be happy about it. 😄

**Comment by maartentibau** [comment]
That is a VERY true remark! Maybe I should make something like https://www.svgporn.com, but I haven't found the time for that (yea... lame excuse).

Anyhow... I really need to create this!

**Comment by martinakraus** [comment]
Count me in. I love the idea!!!

**Comment by tomastrajan** [comment]
Definitely, simple GitHub pages static site which shows all the logos next to each other ;)

**Comment by meeroslav** [comment]
For the time being, adding it to the README.md page would already be great

**Comment by fmalcher** [comment]
I did a thing: https://fmalcher.github.io/angular-logo-gallery/

Uses the GitHub API to request the list of files in the folder.
I'm sure it would have worked with a static Jekyll page as well, but an Angular application to display Angular logos felt more than right for me 😇

This is still in a VERY early stage – just for demo purposes! (And I think we should not post this somewhere before it's not finished 😉 )

**Comment by maartentibau** [comment]
OMG!!! This really is nice!
I’m lost for words... how nice of you to set this up.

I will have a look at you source. But this really looks already REALLY nice!! 🙏🙏

**Comment by fmalcher** [comment]
Maybe let's chat on twitter, can you send me a DM?
