### ISSUE TITLE
heidelberg logo is doubled

### ISSUE THREAD

**Issue by fmalcher** [maartentibau/angular-logos#38]
https://github.com/maartentibau/angular-logos/blob/master/logos/ng-heidelberg.svg
https://github.com/maartentibau/angular-logos/blob/master/logos/angular-heidelberg.svg

The Angular heidelberg logo is in the list two times.

**Comment by maartentibau** [comment]
Which one do you prefer? 😄

**Comment by fmalcher** [comment]
The first commit by @JohannesHoppe 😇😄
