### ISSUE TITLE
provide PR template with info for contributors

### ISSUE THREAD

**Issue by fmalcher** [maartentibau/angular-logos#65]
Add a PR template where PR creators can get infos:
- image as SVG
- vector graphics and no pixels
- if you like, add metadata => here's the skeleton

**Comment by dianjuar** [comment]
I was about to open an issue suggesting this :smile:. What about:


```
# Logo:
<!-- Put an image to view your awesome logo -->

# Information (metadata):

- Name: <!-- The name of your organization/project -->
- Description: <!-- A short description that tells organization/project do -->
- Url: <!-- The URL's organization/project -->

# Other:
```

---

# Logo


# Information (optional):

- Name: 
- Description: 
- Url: 

# Other:

**Comment by dianjuar** [comment]
You said
> - image as SVG
> - vector graphics and no pixels

- In a PR or Issue in GitHub, you can't upload an SVG image 
  - ![image](https://user-images.githubusercontent.com/7026066/73067898-d98abd00-3e77-11ea-959d-fc92a43e151d.png)
- I didn't get _vector graphics and no pixels_

**Comment by fmalcher** [comment]
Thanks, @dianjuar !

> In a PR or Issue in GitHub, you can't upload an SVG image 

I didn't mean to upload the image to the PR on GitHub but that the image should be a SVG within the branch.

> I didn't get vector graphics and no pixels

This was just notes and of course we need to elaborate a bit on this 🙂
We had some submissions that were SVGs but contained pixel graphics instead of vectors.
For example take a look at [Angular Belarus](https://raw.githubusercontent.com/maartentibau/angular-logos/master/logos/angular-belarus.svg) or [5 things angular](https://raw.githubusercontent.com/maartentibau/angular-logos/master/logos/5-things-angular.svg).

**Comment by dianjuar** [comment]
Ok, so you basically are saying that the PR maker should be aware of what is submitting.

I think that a simple solution could be a _PR Checklist_ and putting all together could be:

---
```
# PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The logo is an SVG
- [ ] The logo doesn't contain vector graphics

# Logo:
<!-- Put an image to view your awesome logo -->

# Information (metadata):

- Name: <!-- The name of your organization/project -->
- Description: <!-- A short description that tells organization/project do -->
- Url: <!-- The URL's organization/project -->

# Other:
```


# PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The logo is an SVG
- [ ] The logo doesn't contain vector graphics

# Logo:


# Information (metadata):

- Name: 
- Description: 
- Url: 

# Other:

**Comment by maartentibau** [comment]
Name is a required field, the others are optional.

Also, we should add:
- createdBy (now this field is called creator)
- license (would maybe also make this required?)

I would not make a checkbox. I would just put a statement saying what the “guidelines” are for a correct logo format.

The source code of every logo is being reviewed on every PR anyway, so don’t really see the need for the checkboxes.

**Comment by fmalcher** [comment]
My intended purpose of the PR template is to inform people about what should be part of the PR.
This CAN be through a checkbox but a simple text can also be enough. The goal should be that people review their file by theirselves and if they want, also add the metadata (which should not be too much for most people). Thus, I'd add a sentence like "If you want, you can already put the metadata into the metadata.json file. If not, we'll fill this in for you."
