### ISSUE TITLE
TLS/SSL issue with the site: www.angularlogos.com

### ISSUE THREAD

**Issue by doggy8088** [maartentibau/angular-logos#69]
In your repo, you setup a link like this https://www.angularlogos.com which is configured a wrong tls/ssl certificate. You should change the link to https://angularlogos.com or update the certificate.

![image](https://user-images.githubusercontent.com/88981/73122856-6a6eaf00-3fc4-11ea-9336-45f9cc5df491.png)

**Comment by maartentibau** [comment]
I've set a `CNAME` on the `www` in my domain settings, to `maartentibau.github.io` I hope that will slove this issue.

**Comment by doggy8088** [comment]
@maartentibau No, it's not solving the issue. See [this](https://www.angularlogos.com/). But I saw you changed the link from github repo. So I close the issue.
