### ISSUE TITLE
dutch-angular-group has margin

### ISSUE THREAD

**Issue by fmalcher** [maartentibau/angular-logos#78]
[dutch-angular-group.svg](https://github.com/maartentibau/angular-logos/blob/master/logos/dutch-angular-group.svg) has some top and bottom margin around the logo which makes the page display a bit untidy.

**Comment by Jefiozie** [comment]
Can you assign me to this issue will have a look at it later this week. Thanks!

**Comment by fmalcher** [comment]
Sure, thank you 🙂
