### ISSUE TITLE
adding  max-width: 100%; for images

### ISSUE THREAD

**Issue by OmarioHassan** [maartentibau/angular-logos#87]
![image](https://user-images.githubusercontent.com/8146344/87617393-af73d280-c717-11ea-90f3-91ad99f0de91.png)

to make it like this:

![image](https://user-images.githubusercontent.com/8146344/87617409-b864a400-c717-11ea-8905-9d03fefd5426.png)

**Comment by fmalcher** [comment]
Good catch! Do you think you could submit a PR that adds this? Thank you! 🙂

**Comment by OmarioHassan** [comment]
Sure i will
